### PR TITLE
Add other source types

### PR DESCRIPTION
**Pull request by mariogiampieri**

### CODE REVIEW

**Comment by mariogiampieri** [comment]
I tested vector tile, image, and raster tile source types successfully in `FullPageMap` and started to abstract out some of the bits that would be needed in the other map types as well- I can finish refactoring those tomorrow but in the meantime this should be enough to write the next tuto

**Comment by mariogiampieri** [comment]
realized i didn't fully implement for the inline map type or scrollytelling, but both should be good to go. I had tested fully in full page map and there are examples of the other layers types there

**Comment by mariogiampieri** [comment]
I added the toggle layers thing for inline maps as well per #13

**Review by darebrawley — APPROVED** [review]
Looks good! Still figuring out whether I'll require folks to sync this for tutorial 9 because it seems like there are merge conflicts if anyone has edited the inline maps mdx file.

**Comment by mariogiampieri** [comment]
Hm maybe I can walk those changes back for this and save them for another branch. I can take a look soon On Nov 17, 2024, at 9:42 AM, darebrawley ***@***.***> wrote:﻿
@darebrawley approved this pull request.

Looks good! Still figuring out whether I'll require folks to sync this for tutorial 9 because it seems like there are merge conflicts if anyone has edited the inline maps mdx file.

**Comment by mariogiampieri** [comment]
Looks like it's just a linting thing in that file, i will undo

**Comment by mariogiampieri** [comment]
fwiw @darebrawley after walking those changes back in the file i was able to make changes in my personal testing fork in that file and then sync w/o issue. agreed though that we want to minimize the extra headache so we could always just talk about that next class or forward some guidance to help with that

**Pull request merged**
